### ISSUE TITLE
ICQ relayer stops sending a batch

### ISSUE THREAD

**Issue by RaulBernal** [ingenuity-build/interchain-queries#23]
```
ts=2023-05-23T08:27:35.581190896Z caller=run.go:333 chain=quicksilver-2 src_chain=osmosis-1 worker=historic msg="Handling request" type=cosmos.staking.v1beta1.Query/Validators id=c6df5a67a1ef74b31fe3fbfbf271dcf54f7d98cf9b746c2ac6855d1727cfb868 height=10762301
ts=2023-05-23T08:27:35.592653722Z caller=run.go:333 chain=quicksilver-2 src_chain=regen-1 worker=historic msg="Handling request" type=cosmos.staking.v1beta1.Query/Validators id=c6df5a67a1ef74b31fe3fbfbf271dcf54f7d98cf9b746c2ac6855d1727cfb868 height=10762301
ts=2023-05-23T08:27:42.137338766Z caller=run.go:592 worker=flusher chain=quicksilver-2 msg="Sending batch of 2 messages"
ts=2023-05-23T08:27:42.137421931Z caller=run.go:662 worker=flusher chain=quicksilver-2 msg="Added SubmitResponse message" id=c6df5a67a1ef74b31fe3fbfbf271dcf54f7d98cf9b746c2ac6855d1727cfb868
ts=2023-05-23T08:27:45.765372879Z caller=run.go:636 worker=flusher chain=quicksilver-2 msg="Sent batch of 1 (deduplicated) messages"
panic: panic(6): post failed: Post "http://x5.x17.10x.2xx:xx67": EOF

goroutine 244 [running]:
github.com/ingenuity-build/interchain-queries/pkg/runner.doRequest({{0xc0012aa610, 0xd}, {0xc0004051a0, 0xc}, {0xc0004051e8, 0x7}, {0xc001bc8040, 0x40}, {0xc001051fb0, 0x11}, ...}, ...)
	/home/xxxx/interchain-queries/pkg/runner/run.go:329 +0x25b9
github.com/ingenuity-build/interchain-queries/pkg/runner.doRequestWithMetrics({{0xc0012aa610, 0xd}, {0xc0004051a0, 0xc}, {0xc0004051e8, 0x7}, {0xc001bc8040, 0x40}, {0xc001051fb0, 0x11}, ...}, ...)
	/home/xxx/interchain-queries/pkg/runner/run.go:314 +0x145
created by github.com/ingenuity-build/interchain-queries/pkg/runner.handleEvent
	/home/xxx/interchain-queries/pkg/runner/run.go:256 +0x845
```

Release: `icq/v0.8.2`

**Comment by RaulBernal** [comment]
Again but in the Osmosis side 
```
ts=2023-05-23T09:00:06.443770185Z caller=run.go:333 worker=chainClient chain=quicksilver-2 src_chain=osmosis-1 msg="Handling request" type=cosmos.staking.v1beta1.Query/Validators id=f8bf6e71558f07d3da964fe636de99cfe152a4c61ac5ec0641615a477c262200 height=9755362
ts=2023-05-23T09:00:12.721275184Z caller=run.go:592 worker=flusher chain=quicksilver-2 msg="Sending batch of 2 messages"
ts=2023-05-23T09:00:12.721405486Z caller=run.go:662 worker=flusher chain=quicksilver-2 msg="Added SubmitResponse message" id=f8bf6e71558f07d3da964fe636de99cfe152a4c61ac5ec0641615a477c262200
ts=2023-05-23T09:00:16.640380426Z caller=run.go:636 worker=flusher chain=quicksilver-2 msg="Sent batch of 1 (deduplicated) messages"
panic: panic(6): post failed: Post "http://osmo:46657": EOF

goroutine 1173 [running]:
github.com/ingenuity-build/interchain-queries/pkg/runner.doRequest({{0xc001028fb0, 0xd}, {0xc00056ff30, 0xc}, {0xc000faa040, 0x9}, {0xc00166ec00, 0x40}, {0xc0016da6f0, 0x27}, ...}, ...)
	/home/xxxx/interchain-queries/pkg/runner/run.go:329 +0x25b9
github.com/ingenuity-build/interchain-queries/pkg/runner.doRequestWithMetrics({{0xc001028fb0, 0xd}, {0xc00056ff30, 0xc}, {0xc000faa040, 0x9}, {0xc00166ec00, 0x40}, {0xc0016da6f0, 0x27}, ...}, ...)
	/home/xxx/interchain-queries/pkg/runner/run.go:314 +0x145
created by github.com/ingenuity-build/interchain-queries/pkg/runner.handleEvent
	/home/xxx/interchain-queries/pkg/runner/run.go:256 +0x845
```

**Comment by RaulBernal** [comment]
and again, this is the last trace it put:
```
ts=2023-05-23T09:35:59.27921337Z caller=run.go:636 worker=flusher chain=quicksilver-2 msg="Sent batch of 4 (deduplicated) messages"
ts=2023-05-23T09:35:59.279353511Z caller=run.go:592 worker=flusher chain=quicksilver-2 msg="Sending batch of 6 messages"
ts=2023-05-23T09:35:59.279489365Z caller=run.go:653 worker=flusher chain=quicksilver-2 msg="Added ClientUpdate message" height=1-9755738
ts=2023-05-23T09:35:59.279522416Z caller=run.go:662 worker=flusher chain=quicksilver-2 msg="Added SubmitResponse message" id=fca174e76c0dcf4d89fe73bbc254d76ed590dadd5c19fe23285b411d8c586d2f
ts=2023-05-23T09:35:59.279538506Z caller=run.go:662 worker=flusher chain=quicksilver-2 msg="Added SubmitResponse message" id=c45dc3d27735b527815c425b6d1a61c21ffb0fbb63f579ff81477d2cf48fc16a
panic: panic(6): post failed: Post "http://osmosis": EOF

goroutine 4575 [running]:
github.com/ingenuity-build/interchain-queries/pkg/runner.doRequest({{0xc0012bb6d0, 0xd}, {0xc0004da500, 0xc}, {0xc0004da760, 0x9}, {0xc000527040, 0x40}, {0xc001ef5038, 0x11}, ...}, ...)
	/home/xxxx/interchain-queries/pkg/runner/run.go:329 +0x25b9
github.com/ingenuity-build/interchain-queries/pkg/runner.doRequestWithMetrics({{0xc0012bb6d0, 0xd}, {0xc0004da500, 0xc}, {0xc0004da760, 0x9}, {0xc000527040, 0x40}, {0xc001ef5038, 0x11}, ...}, ...)
	/home/xxxx/interchain-queries/pkg/runner/run.go:314 +0x145
created by github.com/ingenuity-build/interchain-queries/pkg/runner.handleEvent
	/home/xxx/interchain-queries/pkg/runner/run.go:256 +0x845
```

**Comment by RaulBernal** [comment]
Hi @joe-bowman, this is with release `v0.9.1`

```
 panic: panic(6): post failed: Post "http://95.217.109.223:6767": EOF
Jun 03 01:41:03 vmi1139639.contaboserver.net docker[192712]: goroutine 261 [running]:
Jun 03 01:41:03 vmi1139639.contaboserver.net docker[192712]: github.com/ingenuity-build/interchain-queries/pkg/runner.handleEvent({{0xc00589d2e0, 0x20}, {0x189c4a0, 0xc006d72700}, 0xc005ce0150}, {0x1fefe60, 0xc004fb1360}, {{0xc001389e00}, {0xc001389e90}, {0xc001389f50}, ...})
Jun 03 01:41:03 vmi1139639.contaboserver.net docker[192712]:         /src/app/pkg/runner/run.go:345 +0xf99
Jun 03 01:41:03 vmi1139639.contaboserver.net docker[192712]: created by github.com/ingenuity-build/interchain-queries/pkg/runner.Run.func3
Jun 03 01:41:03 vmi1139639.contaboserver.net docker[192712]:         /src/app/pkg/runner/run.go:145 +0xc8

&&&&


Jun 03 02:05:59 vmi1139639.contaboserver.net docker[196112]: panic: panic(6): post failed: Post "http://xxx.xxx.xx.3:6767": EOF
Jun 03 02:05:59 vmi1139639.contaboserver.net docker[196112]: goroutine 248 [running]:
Jun 03 02:05:59 vmi1139639.contaboserver.net docker[196112]: github.com/ingenuity-build/interchain-queries/pkg/runner.handleHistoricRequests({0xc005effd40?, 0x1, 0x1}, {0xc00013ff70, 0xd}, {0x1fefe60, 0xc00535b8b0}, {{0xc001410480}, {0xc001410510}, {0xc0014105d0}, ...})
Jun 03 02:05:59 vmi1139639.contaboserver.net docker[196112]:         /src/app/pkg/runner/run.go:256 +0xbe5
Jun 03 02:05:59 vmi1139639.contaboserver.net docker[196112]: created by github.com/ingenuity-build/interchain-queries/pkg/runner.Run.func5
Jun 03 02:05:59 vmi1139639.contaboserver.net docker[196112]:         /src/app/pkg/runner/run.go:197 +0x6a5
Jun 03 02:06:00 vmi1139639.contaboserver.net systemd[1]: interchain-queries.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 03 02:06:00 vmi1139639.contaboserver.net systemd[1]: interchain-queries.service: Failed with result 'exit-code'.
Jun 03 02:06:00 vmi1139639.contaboserver.net systemd[1]: interchain-queries.service: Scheduled restart job, restart counter is at 19.
```
